### ISSUE TITLE
Date field format mask

### ISSUE THREAD

**Issue by khanengineer** [APEXGru/ExtendToolbarInputFIeld#2]
Thank you very much for your time and effort on developing this plugin. It makes it very easy for us who are not too familiar with JavaScripting. I've a quick question for you, is there a way to change the date format for the date field that is added to the IG toolbar? Initially it shows the date in DD-MON-YYYY format, however, when a date is selected from date picker the date format changes to DD-MM-YYYY. I was wondering if we can have some control over the formatting of the date. If not, then keeping it consistent, i.e., DD-MON-YYYY would really help.

Please advise.

Thanks.

**Comment by APEXGru** [comment]
Hi,
You can easily change the date format in line 83 of the JavaScript file. In your example it should be : dd-M-yy.
It would be nice to get the date format the Application Date Format - but there is no easy way to do so (apart from if the Application Date Format = x, then the JS DateFormat = y).
Cheers
Roel

**Comment by khanengineer** [comment]
Thanks, that worked!
